language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypy3"
matrix:
  allow-failures:
    - python: "3.5-dev"
    - python: "nightly"
  fast_finish: true
# command to run tests
install:
  - "pip install MySQL-python"
script: python setup.py test
sudo: false
